[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn christ_king_church.wsgi"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10